export const ARENA_WIDTH = 1280;
export const ARENA_HEIGHT = 720;
export const GROUND_Y = 592;
export const ROUND_TIME = 60;
export const WIN_ROUNDS = 2;
export const INPUT_BUFFER_FRAMES = 12;
export const PRE_ROUND_FRAMES = 90;
export const POST_ROUND_FRAMES = 150;
export const MAX_GUARD = 100;

export const MOVES = {
  jab: {
    id: "jab",
    label: "Jab",
    button: "light",
    startup: 4,
    active: 2,
    recovery: 8,
    hitstun: 12,
    blockstun: 8,
    damage: 6,
    guardDamage: 5,
    pushback: 18,
    velocity: 0,
    offsetX: 56,
    offsetY: -98,
    width: 48,
    height: 28,
    hitLevel: "high",
    cancelOnHit: ["medium", "heavy"],
    cancelOnBlock: ["medium"],
    cancelWindowStart: 5,
    cancelWindowEnd: 9,
    whiffCancel: [],
  },
  lowKick: {
    id: "lowKick",
    label: "Low Kick",
    button: "medium",
    startup: 6,
    active: 3,
    recovery: 11,
    hitstun: 14,
    blockstun: 10,
    damage: 8,
    guardDamage: 8,
    pushback: 28,
    velocity: 0,
    offsetX: 60,
    offsetY: -48,
    width: 56,
    height: 22,
    hitLevel: "low",
    cancelOnHit: ["heavy", "special"],
    cancelOnBlock: [],
    cancelWindowStart: 7,
    cancelWindowEnd: 12,
    whiffCancel: [],
  },
  stepKick: {
    id: "stepKick",
    label: "Step Kick",
    button: "heavy",
    startup: 9,
    active: 3,
    recovery: 15,
    hitstun: 18,
    blockstun: 12,
    damage: 11,
    guardDamage: 10,
    pushback: 42,
    velocity: 3.4,
    offsetX: 76,
    offsetY: -92,
    width: 74,
    height: 30,
    hitLevel: "mid",
    cancelOnHit: ["special"],
    cancelOnBlock: [],
    cancelWindowStart: 10,
    cancelWindowEnd: 14,
    whiffCancel: [],
  },
  antiAir: {
    id: "antiAir",
    label: "Rising Elbow",
    button: "light",
    startup: 5,
    active: 4,
    recovery: 14,
    hitstun: 20,
    blockstun: 11,
    damage: 9,
    guardDamage: 7,
    pushback: 24,
    velocity: 0,
    offsetX: 52,
    offsetY: -142,
    width: 42,
    height: 62,
    hitLevel: "antiAir",
    cancelOnHit: [],
    cancelOnBlock: [],
    cancelWindowStart: 0,
    cancelWindowEnd: 0,
    whiffCancel: [],
    antiAirOnly: true,
  },
  fireball: {
    id: "fireball",
    label: "Palm Burst",
    button: "heavy",
    startup: 11,
    active: 2,
    recovery: 17,
    hitstun: 16,
    blockstun: 12,
    damage: 10,
    guardDamage: 11,
    pushback: 16,
    velocity: 0,
    offsetX: 62,
    offsetY: -94,
    width: 30,
    height: 32,
    hitLevel: "mid",
    cancelOnHit: [],
    cancelOnBlock: [],
    cancelWindowStart: 12,
    cancelWindowEnd: 14,
    whiffCancel: [],
    projectile: {
      speed: 10,
      life: 78,
      width: 36,
      height: 24,
    },
  },
  overhead: {
    id: "overhead",
    label: "Axe Heel",
    button: "medium",
    startup: 14,
    active: 3,
    recovery: 16,
    hitstun: 17,
    blockstun: 9,
    damage: 12,
    guardDamage: 9,
    pushback: 34,
    velocity: 1.4,
    offsetX: 68,
    offsetY: -118,
    width: 52,
    height: 44,
    hitLevel: "overhead",
    cancelOnHit: ["special"],
    cancelOnBlock: [],
    cancelWindowStart: 15,
    cancelWindowEnd: 17,
    whiffCancel: [],
  },
};

export const ATTACK_INPUTS = {
  light: [
    { id: "antiAir", when: (fighter) => fighter.input.up && fighter.distance < 140 },
    { id: "jab", when: () => true },
  ],
  medium: [
    { id: "overhead", when: (fighter, opponent) => opponent.crouching && fighter.distance < 140 },
    { id: "lowKick", when: (fighter) => fighter.crouching || fighter.distance < 168 },
    { id: "overhead", when: () => true },
  ],
  heavy: [
    { id: "fireball", when: (fighter) => fighter.distance > 200 && fighter.onGround },
    { id: "stepKick", when: () => true },
  ],
};
