export const TOWER_TYPES = Object.freeze({
  splash: {
    label: "Splash",
    roleLabel: "Area burst",
    family: "splash",
    cost: 60,
    rangeCells: 2.7,
    fireRate: 1.15,
    projectileSpeed: 430,
    damage: 24,
    impactRadiusCells: 1.45,
    arcHeight: 0.28,
    color: "#7df3ff",
    glow: "rgba(125, 243, 255, 0.34)",
    trail: "rgba(125, 243, 255, 0.8)",
  },
  splash_prism: {
    label: "Prism Splash",
    roleLabel: "Fracture bloom",
    family: "splash",
    cost: 82,
    rangeCells: 3.15,
    fireRate: 1.32,
    projectileSpeed: 460,
    damage: 28,
    impactRadiusCells: 1.7,
    arcHeight: 0.32,
    color: "#9ef9ff",
    glow: "rgba(126, 255, 247, 0.34)",
    trail: "rgba(126, 255, 247, 0.84)",
  },
  splash_breach: {
    label: "Breach Splash",
    roleLabel: "Siegebreaker",
    family: "splash",
    cost: 94,
    rangeCells: 3.35,
    fireRate: 1.05,
    projectileSpeed: 495,
    damage: 34,
    impactRadiusCells: 1.95,
    arcHeight: 0.28,
    revealHidden: true,
    color: "#d4fffb",
    glow: "rgba(125, 243, 255, 0.42)",
    trail: "rgba(125, 243, 255, 0.9)",
  },
  slow: {
    label: "Slow",
    roleLabel: "Frost field",
    family: "slow",
    cost: 50,
    rangeCells: 3.2,
    fireRate: 0.95,
    projectileSpeed: 390,
    damage: 11,
    impactRadiusCells: 0.55,
    slowFactor: 0.55,
    slowDuration: 1.8,
    controlBonus: 0.12,
    color: "#7d8dff",
    glow: "rgba(125, 141, 255, 0.34)",
    trail: "rgba(125, 141, 255, 0.82)",
  },
  slow_fracture: {
    label: "Fracture Slow",
    roleLabel: "Lockfield",
    family: "slow",
    cost: 68,
    rangeCells: 3.6,
    fireRate: 1.08,
    projectileSpeed: 420,
    damage: 13,
    impactRadiusCells: 0.7,
    slowFactor: 0.42,
    slowDuration: 2.3,
    controlBonus: 0.16,
    color: "#98a4ff",
    glow: "rgba(125, 141, 255, 0.38)",
    trail: "rgba(125, 141, 255, 0.86)",
  },
  slow_glacier: {
    label: "Glacier Slow",
    roleLabel: "Permafrost",
    family: "slow",
    cost: 88,
    rangeCells: 3.9,
    fireRate: 0.88,
    projectileSpeed: 400,
    damage: 15,
    impactRadiusCells: 0.8,
    slowFactor: 0.36,
    slowDuration: 2.7,
    controlBonus: 0.2,
    revealHidden: true,
    color: "#b8c0ff",
    glow: "rgba(170, 178, 255, 0.42)",
    trail: "rgba(170, 178, 255, 0.9)",
  },
  burn: {
    label: "Burn",
    roleLabel: "Damage over time",
    family: "burn",
    cost: 70,
    rangeCells: 2.9,
    fireRate: 0.82,
    projectileSpeed: 410,
    damage: 8,
    impactRadiusCells: 0.6,
    burnDps: 18,
    burnDuration: 3.2,
    burnTickInterval: 0.25,
    burnAmplify: 1,
    color: "#ffae57",
    glow: "rgba(255, 174, 87, 0.34)",
    trail: "rgba(255, 174, 87, 0.82)",
  },
  burn_solar: {
    label: "Solar Burn",
    roleLabel: "Incinerator",
    family: "burn",
    cost: 92,
    rangeCells: 3.15,
    fireRate: 0.96,
    projectileSpeed: 448,
    damage: 11,
    impactRadiusCells: 0.75,
    burnDps: 24,
    burnDuration: 3.8,
    burnTickInterval: 0.22,
    burnAmplify: 1.16,
    color: "#ffd08f",
    glow: "rgba(255, 174, 87, 0.4)",
    trail: "rgba(255, 174, 87, 0.88)",
  },
  burn_inferno: {
    label: "Inferno Burn",
    roleLabel: "Ember crown",
    family: "burn",
    cost: 110,
    rangeCells: 3.35,
    fireRate: 0.75,
    projectileSpeed: 470,
    damage: 13,
    impactRadiusCells: 0.82,
    burnDps: 30,
    burnDuration: 4.2,
    burnTickInterval: 0.2,
    burnAmplify: 1.28,
    revealHidden: true,
    color: "#ffe6b1",
    glow: "rgba(255, 174, 87, 0.48)",
    trail: "rgba(255, 198, 130, 0.92)",
  },
  needle: {
    label: "Needle",
    roleLabel: "Focus line",
    family: "needle",
    cost: 66,
    rangeCells: 3.4,
    fireRate: 2.3,
    projectileSpeed: 610,
    damage: 10,
    impactRadiusCells: 0.34,
    markDuration: 1.6,
    markEnergy: 1,
    critBonus: 1.18,
    color: "#6ef8d7",
    glow: "rgba(110, 248, 215, 0.36)",
    trail: "rgba(110, 248, 215, 0.82)",
  },
  needle_quasar: {
    label: "Quasar Needle",
    roleLabel: "Rapid-fire single-target DPS",
    family: "needle",
    cost: 88,
    rangeCells: 3.85,
    fireRate: 3.85,
    projectileSpeed: 670,
    damage: 8,
    impactRadiusCells: 0.3,
    markDuration: 1.95,
    markEnergy: 1.5,
    critBonus: 1.32,
    color: "#a2ffee",
    glow: "rgba(110, 248, 215, 0.42)",
    trail: "rgba(110, 248, 215, 0.9)",
  },
  needle_lance: {
    label: "Lance Needle",
    roleLabel: "Pierce cutter",
    family: "needle",
    cost: 98,
    rangeCells: 4.05,
    fireRate: 2.95,
    projectileSpeed: 700,
    damage: 12,
    impactRadiusCells: 0.36,
    markDuration: 1.5,
    markEnergy: 1.25,
    critBonus: 1.24,
    color: "#d3fff2",
    glow: "rgba(110, 248, 215, 0.46)",
    trail: "rgba(110, 248, 215, 0.92)",
  },
  relay: {
    label: "Relay",
    roleLabel: "Energy conduit",
    family: "relay",
    cost: 58,
    rangeCells: 3.05,
    fireRate: 0.88,
    projectileSpeed: 430,
    damage: 6,
    impactRadiusCells: 0.45,
    markDuration: 2.1,
    scanReward: 1,
    energyPulse: 2,
    markEnergy: 1,
    color: "#ffdf7a",
    glow: "rgba(255, 223, 122, 0.34)",
    trail: "rgba(255, 223, 122, 0.82)",
  },
  relay_chain: {
    label: "Chain Relay",
    roleLabel: "Scan lattice",
    family: "relay",
    cost: 76,
    rangeCells: 3.45,
    fireRate: 1.02,
    projectileSpeed: 470,
    damage: 7,
    impactRadiusCells: 0.5,
    markDuration: 2.8,
    scanReward: 2,
    energyPulse: 3,
    markEnergy: 1.5,
    scanRadiusCells: 4.2,
    color: "#ffe79d",
    glow: "rgba(255, 223, 122, 0.4)",
    trail: "rgba(255, 223, 122, 0.88)",
  },
  relay_capacitor: {
    label: "Capacitor Relay",
    roleLabel: "Energy-generation support",
    family: "relay",
    cost: 92,
    rangeCells: 3.7,
    fireRate: 0.92,
    projectileSpeed: 500,
    damage: 8,
    impactRadiusCells: 0.54,
    markDuration: 2.5,
    scanReward: 2,
    energyPulse: 4,
    markEnergy: 2,
    color: "#fff0b3",
    glow: "rgba(255, 223, 122, 0.46)",
    trail: "rgba(255, 223, 122, 0.92)",
  },
  disrupt: {
    label: "Disrupt",
    roleLabel: "Shield breaker",
    family: "disrupt",
    cost: 62,
    rangeCells: 3.1,
    fireRate: 1.05,
    projectileSpeed: 440,
    damage: 7,
    impactRadiusCells: 0.5,
    shieldBreak: 14,
    exposeDuration: 1.2,
    markDuration: 1.35,
    color: "#d38cff",
    glow: "rgba(211, 140, 255, 0.34)",
    trail: "rgba(211, 140, 255, 0.82)",
  },
  disrupt_breaker: {
    label: "Breaker Disrupt",
    roleLabel: "Shield rupture",
    family: "disrupt",
    cost: 84,
    rangeCells: 3.45,
    fireRate: 1.12,
    projectileSpeed: 480,
    damage: 9,
    impactRadiusCells: 0.56,
    shieldBreak: 28,
    exposeDuration: 1.8,
    markDuration: 1.9,
    color: "#ecbbff",
    glow: "rgba(211, 140, 255, 0.4)",
    trail: "rgba(211, 140, 255, 0.88)",
  },
  disrupt_veil: {
    label: "Veil Disrupt",
    roleLabel: "Vulnerability veil",
    family: "disrupt",
    cost: 96,
    rangeCells: 3.65,
    fireRate: 1,
    projectileSpeed: 500,
    damage: 10,
    impactRadiusCells: 0.6,
    shieldBreak: 20,
    exposeDuration: 2.2,
    markDuration: 2.4,
    color: "#f1d0ff",
    glow: "rgba(211, 140, 255, 0.46)",
    trail: "rgba(211, 140, 255, 0.92)",
  },
});

export const TOWER_UPGRADES = Object.freeze({
  splash: {
    label: "Splash",
    branches: [
      {
        id: "prism",
        label: "Prism Bloom",
        finalRole: "Fracture bloom",
        type: "splash_prism",
        cost: 82,
        note: "Wider radius and quicker follow-up shots.",
      },
      {
        id: "breach",
        label: "Breach Lens",
        finalRole: "Siegebreaker",
        type: "splash_breach",
        cost: 94,
        note: "Harder hits with the largest blast.",
      },
    ],
  },
  slow: {
    label: "Slow",
    branches: [
      {
        id: "fracture",
        label: "Fracture Net",
        finalRole: "Lockfield",
        type: "slow_fracture",
        cost: 68,
        note: "Stronger slow with a wider catch radius.",
      },
      {
        id: "glacier",
        label: "Glacier Coil",
        finalRole: "Permafrost",
        type: "slow_glacier",
        cost: 88,
        note: "Longer lock and broader control range.",
      },
    ],
  },
  burn: {
    label: "Burn",
    branches: [
      {
        id: "solar",
        label: "Solar Furnace",
        finalRole: "Incinerator",
        type: "burn_solar",
        cost: 92,
        note: "Higher uptime and stronger burn ticks.",
      },
      {
        id: "inferno",
        label: "Inferno Crown",
        finalRole: "Ember crown",
        type: "burn_inferno",
        cost: 110,
        note: "Longest burn and the hardest edge damage.",
      },
    ],
  },
  needle: {
    label: "Needle",
    branches: [
      {
        id: "quasar",
        label: "Quasar Spike",
        finalRole: "Rapid-fire single-target DPS",
        type: "needle_quasar",
        cost: 88,
        note: "Fastest fire cycle and the best mark chaining.",
      },
      {
        id: "lance",
        label: "Lance Needle",
        finalRole: "Pierce cutter",
        type: "needle_lance",
        cost: 98,
        note: "Long range precision with stronger finish hits.",
      },
    ],
  },
  relay: {
    label: "Relay",
    branches: [
      {
        id: "chain",
        label: "Chain Relay",
        finalRole: "Scan lattice",
        type: "relay_chain",
        cost: 76,
        note: "Better mark uptime and more scan rewards.",
      },
      {
        id: "capacitor",
        label: "Capacitor Web",
        finalRole: "Energy-generation support",
        type: "relay_capacitor",
        cost: 92,
        note: "Highest energy pulse and the strongest chain reward.",
      },
    ],
  },
  disrupt: {
    label: "Disrupt",
    branches: [
      {
        id: "breaker",
        label: "Breaker Core",
        finalRole: "Shield rupture",
        type: "disrupt_breaker",
        cost: 84,
        note: "Big shield strip and longer expose window.",
      },
      {
        id: "veil",
        label: "Vulnerability Veil",
        finalRole: "Vulnerability veil",
        type: "disrupt_veil",
        cost: 96,
        note: "Best debuff uptime and strongest follow-up exposure.",
      },
    ],
  },
});
