export const CONFIG = {
  canvasWidth: 1600,
  canvasHeight: 900,
  groundY: 730,
  groundAmplitude: 0,
  gravity: 1800,
  timeStep: 1 / 60,
  solverIterations: 10,
  groundFriction: 0.82,
  jointStiffness: 0.72,
  jointDamping: 0.14,
  torqueScale: 620,
  recoverTorqueScale: 0.38,
  maxJointTorque: 1,
  limbLengths: {
    thigh: 72,
    calf: 68,
    sole: 34,
    torso: 92,
  },
  massProfile: {
    torso: 8.5,
    thigh: 3.2,
    calf: 2.5,
    sole: 1.1,
  },
  controlChannels: {
    leftThigh: ["q", "a"],
    rightThigh: ["w", "s"],
    leftCalf: ["o", "k"],
    rightCalf: ["p", "l"],
    leftSole: ["z", ","],
    rightSole: ["x", "."],
  },
  maxLean: 1.15,
  fallAngle: 1.35,
  startSpeed: 140,
  distanceScale: 0.25,
  hurdleGap: 7,
  hurdleSpawnAhead: 7,
  hurdleWidth: 1.45,
  hurdleHeight: 1.15,
  hurdleWorldWidth: 18,
  hurdleWorldHeight: 84,
  hurdleClearanceLean: 0.72,
  hurdleTorsoClearance: 110,
  hurdleTimingSplit: 28,
  imageBase: "./assets/images",
  art: {
    runner: "./assets/images/runner-mask.svg",
    burst: "./assets/images/faceplant-burst.svg",
  },
  leanFallThreshold: 1.28,
  irrecoverableLean: 1.42,
};
