type BuildObservationTemplateOptions = {
  game?: string;
  sessionDate?: string;
};

type BuildProbeDeckOptions = {
  game?: string;
  sessionDate?: string;
  observationPath?: string;
  reportPath?: string;
  starterDir?: string;
};

export function buildObservationTemplate({
  game = "some-game",
  sessionDate = "2026-04-30",
}: BuildObservationTemplateOptions = {}) {
  return {
    game,
    sessionDate,
    sessionFocus: ["first-contact", "busy-frame", "fail-retry", "impact"],
    evidence: {
      mode: "direct-play",
      sampledRuns: 2,
      sampledFailures: 1,
      sampledRetries: 1,
      sampledBusyFrames: 1,
      sampledEncounters: 2,
      sampledContacts: 4,
      sampledResumeProbes: 1,
      notes: ["short first run plus one targeted replay after death"],
    },
    firstContact: {
      loopComplexity: "low",
      discoverableThroughExperiment: true,
      firstObjectiveClear: true,
      currentGoalEasyToRestate: true,
      nextStepPrescriptive: true,
      controlsReminderAvailable: false,
      objectiveReminderAvailable: true,
      progressSafeHelp: true,
      remapSafe: false,
      upfrontInstructionScreens: 0,
      promptsBeforeMeaningfulPlay: 1,
      blocksFirstMeaningfulInput: false,
      forcedTutorialSteps: 0,
      optionalHelpOnDemand: true,
    },
    earlyLoop: {
      firstMeaningfulInputAt: "00:04",
      secondsToFirstMeaningfulInput: 4,
      firstRiskAt: "00:08",
      secondsToFirstRisk: 8,
      firstRewardAt: "00:12",
      secondsToFirstReward: 12,
      firstRetryOpportunityAt: "00:35",
      secondsToFirstRetryOpportunity: 35,
      notes: "player acts quickly, meets first danger soon after, and sees first payoff before patience runs cold",
    },
    mastery: {
      earlySuccessEarned: true,
      firstSuccessMoment: "00:12",
      successFeedbackClear: true,
      proximalGoalVisible: true,
      progressLegible: true,
      progressRemindersAvailable: true,
      failureImprovementVisible: true,
      choiceCountFirstMinute: 1,
      choicesFeelMeaningful: true,
      autonomySupport: "medium",
      competenceSupport: "high",
      notes: "player gets one clear short goal, earns an early payoff, and chooses between a safer line and a greedier pickup line",
      choicePoints: [
        {
          moment: "00:18",
          label: "safe lane or center pickup",
          choiceType: "risk-reward",
          optionsCount: 2,
          meaningClear: true,
          reversible: false,
          offeredOptions: [
            {
              label: "safe outer lane",
              expectedPayoff: "lower score gain, lower hit risk",
              expectedCost: "skip the bonus pickup and keep the damage boost inactive",
              currentStateComparison: "keeps the current low-pressure route and does not spend the shield pip",
              currentBuildComparison: "fits the current no-boost build by preserving the defensive shield state",
              notes: "conservative route preserves the current build state",
            },
            {
              label: "center pickup line",
              expectedPayoff: "bonus score plus a temporary damage boost",
              expectedCost: "contest the live fire lane and spend the shield pip if clipped",
              currentStateComparison:
                "spends the current shield pip to contest the center line for a stronger follow-up build state",
              currentBuildComparison: "pairs with the current rapid-fire build because the temporary boost amplifies the next burst window",
              notes: "greedy route is advertised as a faster payoff with more pressure",
            },
          ],
          pickedOptionLabel: "center pickup line",
          expectedPayoff: "bonus score plus a temporary damage boost that carries into the next wave",
          actualPayoff:
            "player secures the bonus score, spends the shield pip, and enters the next wave with the damage boost active",
          actualPayoffTiming: "immediate",
          payoffMatchedExpectation: "partial",
          afterPickComparison:
            "boost icon and score spike make the stronger post-pick state visible against the prior no-boost baseline, but the skipped safe route is no longer shown directly",
          afterPickBuildComparison:
            "rapid-fire build becomes more valuable immediately because the boost multiplies the next burst window, while the safer baseline build is no longer visible for side-by-side comparison",
          afterPickComparisonClear: true,
          notes: "tradeoff is readable before commitment and payoff mostly reads back after the pick",
        },
      ],
    },
    readableProgression: {
      proximalGoalVisible: true,
      prerequisiteProgressVisible: true,
      evaluativeReadbackAvailable: true,
      nonComparativeNextStepVisible: true,
      progressFeelsReachable: true,
      progressRemindersAvailable: true,
      notes: "player can see what is already done, what still gates the next step, and what to do next without scoreboard comparison",
    },
    forgiveness: {
      coyoteTimePresent: true,
      inputBufferPresent: true,
      cornerCorrectionPresent: true,
      collisionLeniencyFair: true,
      graceWindowsConsistent: true,
      droppedIntentCausedFailures: false,
      failFeelsStolen: false,
      retryClarifiesMissedTiming: true,
      practiceWindowAvailable: false,
      notes: "the opener preserves obvious late jumps and buffered follow-up actions, while collision stays permissive enough that near-clean lines do not feel stolen",
      moments: [
        {
          at: "00:10",
          challenge: "late edge jump",
          forgivenessType: "coyote-time",
          playerIntent: "jump after leaving the ledge by a fraction",
          intentPreserved: true,
          outcome: "saved",
          retryClarifiedCorrection: true,
          notes: "slightly late jump still lands and reads fair",
        },
        {
          at: "00:31",
          challenge: "tight wall skim",
          forgivenessType: "corner-correction",
          playerIntent: "clear the corner and keep moving",
          intentPreserved: false,
          outcome: "stolen",
          retryClarifiedCorrection: false,
          notes: "avatar clips a corner that looked visually clear",
        },
      ],
    },
    inputDemand: {
      remapSafe: false,
      rapidRepeatedInputPresent: false,
      holdInputPresent: false,
      simultaneousInputPresent: true,
      rapidSequencePresent: false,
      precisionTimingDemandPresent: true,
      pathBasedOrAnalogDemandPresent: false,
      progressionCriticalDemandPresent: true,
      lowerDemandAlternativeAvailable: false,
      difficultyOptionHelps: false,
      demandReadableBeforeFailure: true,
      motorTaxLikelyPrimaryBlocker: false,
      notes: "opening asks for one dodge-plus-fire combination under timing pressure, but the burden stays readable in the sampled route",
      samples: [
        {
          at: "00:26",
          action: "dodge and return fire in the same beat",
          demandType: "simultaneous",
          progressionCritical: true,
          optionalFlavor: false,
          intensity: "medium",
          readableBeforeAttempt: true,
          lowerDemandAlternativeAvailable: false,
          remapWouldNotSolve: true,
          causedFailureOrBlock: false,
          notes: "burden is real, but the sampled player still understands and executes it",
        },
      ],
    },
    controlSurface: {
      remapScope: "partial",
      remapInputsVisible: true,
      remapReflectedInPrompts: false,
      holdToggleAlternativeAvailable: false,
      sensitivityControlsAvailable: true,
      inversionControlsAvailable: true,
      axisControlsAvailable: true,
      gameSpeedReliefAvailable: false,
      timingReliefAvailable: true,
      settingsAndAssistsBoundaryClear: true,
      notes: "log control-surface support separately from motor-tax burden; this session shows tuning surfaces, not a full assist lane",
    },
    settingsAndAssists: {
      reachability: {
        midRunSettingsReachable: true,
        pauseSettingsReachable: true,
        postFailureSettingsReachable: false,
        postFailureAssistReachable: false,
        menuDepth: 2,
        notes: "pause path exposes recovery knobs, but the death screen still jumps straight to retry",
      },
      changeSafety: {
        difficultyAdjustableMidRun: true,
        assistsAdjustableMidRun: false,
        changesApplyWithoutRestart: true,
        progressPreservedWhenChanged: true,
        notes: "difficulty can shift during play without dumping the current checkpoint, but no sampled assist toggle exists",
      },
      reminderPractice: {
        controlsReminderAvailable: true,
        objectiveReminderAvailable: true,
        tutorialReplayAvailable: true,
        practiceReliefAvailable: false,
        promptReadableLongEnoughToUseKnob: true,
        notes: "player can reopen goal and tutorial help, but there is no lower-risk practice lane",
      },
      persistence: {
        assistStatePersistsAcrossRetry: false,
        difficultyStatePersistsAcrossRetry: true,
        retryReentersWithExpectedState: false,
        notes: "retry keeps difficulty but cannot prove assist-state persistence because the death path hides the same knob",
      },
      notes: "keep recovery-trust evidence separate from control remap and tuning evidence",
    },
    criticalElements: [
      {
        name: "health bar",
        location: "top-left",
        importance: "critical",
        readsWithoutText: true,
        contrastStable: true,
        readableUnderMotion: true,
        motionDistraction: "low",
        glanceCost: "low",
        notes: "bar shape readable during movement",
      },
    ],
    cues: [
      {
        name: "incoming-hit arrow",
        importance: "critical",
        nearAction: true,
        redundantSignal: true,
        signalChannels: ["visual", "audio"],
        reliesOnColorAlone: false,
        reliesOnAudioAlone: false,
        telegraphReadable: true,
        requiredResponseObvious: true,
        futurePathVisible: true,
        contrastStable: true,
        readableUnderMotion: true,
        motionDistraction: "low",
        notes: "survives light particle burst",
      },
    ],
    stressFrames: [
      {
        moment: "reward burst after wave clear",
        clutterSource: "particles plus score popup",
        movingBackground: false,
        blinkingContent: false,
        autoUpdatingContent: true,
        cameraMotion: false,
        criticalInfoLost: false,
        cueMasked: false,
        responseStillReadable: true,
        criticalElementsReadableUnderMotion: true,
        tags: ["contrast risk"],
        frameId: "busy-frame-01",
        framePath: ".local/some-game-busy-frames/busy-frame-01.png",
        capturedAtMs: 1200,
        notes: "read stayed intact",
      },
    ],
    competitionMoments: [
      {
        moment: "adds spawn during low-health flash",
        signals: ["incoming-hit arrow", "low-health state", "combo toast"],
        urgentSignalCount: 2,
        dominantReadClear: false,
        responsePriorityClear: false,
        nonCriticalUiCompeting: true,
        notes: "warning stack lands, but combo toast joins and muddies which response matters first",
      },
    ],
    ephemeralMoments: [
      {
        name: "wave-start weapon tip",
        kind: "tutorial",
        importance: "supporting",
        appearsNearAction: true,
        autoDismisses: true,
        dismissSeconds: 3,
        playerControlledAdvance: false,
        reviewableLater: true,
        suppressibleWhenNonCritical: true,
        obstructsCriticalRead: false,
        notes: "prompt is brief, but pause menu repeats it later",
      },
      {
        name: "combo toast",
        kind: "notification",
        importance: "secondary",
        appearsNearAction: true,
        autoDismisses: true,
        dismissSeconds: 2,
        playerControlledAdvance: false,
        reviewableLater: false,
        suppressibleWhenNonCritical: false,
        obstructsCriticalRead: true,
        notes: "reward toast can cross the dodge lane during pressure",
      },
    ],
    clutter: {
      cornerDashboard: false,
      overlapBlocksAction: false,
      backgroundNoiseHurtsRead: false,
      movingUiDistraction: false,
      blinkingUiDistraction: false,
      autoUpdatingUiDistraction: true,
      backgroundMotionDistractsRead: false,
      subtitleOrToastOverlap: false,
      peripheralScanLoad: "low",
    },
    confounders: {
      inputCertainty: "stable",
      responseLatency: "stable",
      cameraSupportsAction: true,
      viewObstructedAtDecision: false,
      autoCameraInterference: false,
      notes: "movement, aiming, and camera stayed trustworthy during pressure sample",
    },
    beats: [
      {
        at: "00:08",
        label: "first dodge lane",
        kind: "teach",
        novelty: "new-verb",
        skills: ["move"],
        practicedBefore: true,
        readable: true,
        activeDemands: 1,
        newDemands: 1,
        stackReadable: true,
        notes: "safe lane before punishment",
      },
      {
        at: "00:26",
        label: "dodge plus fire return",
        kind: "test",
        novelty: "new-combo",
        skills: ["move", "shoot"],
        practicedBefore: false,
        readable: true,
        activeDemands: 2,
        newDemands: 1,
        stackReadable: true,
        notes: "stack begins quickly",
      },
    ],
    retrySeconds: 4,
    returnsToCurrentTestQuickly: true,
    failures: [
      {
        at: "00:31",
        cause: "second projectile hidden behind score popup",
        causeReadable: false,
        correctiveActionClear: false,
        retrySeconds: 4,
        menuLayersBeforeRetry: 1,
        checkpointLossSeconds: 6,
        sourceVisibleOnFail: false,
        returnsToRelevantDecision: true,
        repeatedPenaltyFromSingleMistake: false,
        controlRecoveredBeforeNextHit: true,
        retryContextStable: true,
        notes: "retry fast but death cause muddy",
      },
    ],
    failState: {
      blockingOverlayDuringDeath: false,
      futurePathVisible: false,
      objectiveReminderAvailableAfterFail: true,
    },
    pressure: {
      newThreatBeforeMastery: true,
      overlapSpike: false,
      telegraphReadable: true,
    },
    learningLoop: {
      immediateRetry: true,
      practiceWithoutFailure: false,
      sameSkillRetestedQuickly: true,
      sameLessonStableAcrossRetries: true,
    },
    recoverySupport: {
      quickStartAfterFailure: true,
      difficultyAdjustableAfterFailure: false,
      assistOrSkipAvailable: false,
      tutorialOrHintReopenable: true,
    },
    resumeProbes: [
      {
        breakType: "tab-switch",
        secondsAway: 45,
        resumeSurface: "active run",
        currentGoalRecoverable: true,
        controlsRecoverable: false,
        nextActionClear: true,
        needsMenuDive: false,
        stalePromptMismatch: false,
        notes: "objective still obvious, but no live control refresher after returning",
      },
    ],
    probeOutcomes: [
      {
        probe: "first-contact",
        goal: "reach first meaningful input and restate next step",
        outcome: "success",
        successRating: 4,
        confidence: 6,
        satisfaction: 6,
        frustration: 6,
        mentalDemand: 3,
        timePressure: 2,
        effort: 3,
        blockers: [],
        notes: "player acts quickly and understands the first objective without a tutorial wall",
      },
      {
        probe: "busy-frame",
        goal: "survive one clutter peak and keep one dominant urgent read",
        outcome: "partial",
        successRating: 2,
        confidence: 4,
        satisfaction: 4,
        frustration: 3,
        mentalDemand: 6,
        timePressure: 6,
        effort: 6,
        blockers: ["combo toast competes with dodge read"],
        notes: "critical warning still lands, but non-critical reward UI muddies response priority",
      },
      {
        probe: "fail-retry",
        goal: "decode one death and return to the same lesson quickly",
        outcome: "partial",
        successRating: 2,
        confidence: 3,
        satisfaction: 4,
        frustration: 3,
        mentalDemand: 6,
        timePressure: 5,
        effort: 5,
        blockers: ["death cause hidden by score popup"],
        notes: "retry is fast, but the exact mistake is still muddy",
      },
      {
        probe: "interruption-resume",
        goal: "recover goal, controls, and next action after a short break",
        outcome: "partial",
        successRating: 3,
        confidence: 4,
        satisfaction: 4,
        frustration: 4,
        mentalDemand: 4,
        timePressure: 2,
        effort: 4,
        blockers: ["no live control reminder on return"],
        notes: "goal survives the break better than verb recall does",
      },
      {
        probe: "contact-payoff",
        goal: "land one representative hit and judge payoff clarity",
        outcome: "success",
        successRating: 4,
        confidence: 5,
        satisfaction: 5,
        frustration: 6,
        mentalDemand: 2,
        timePressure: 2,
        effort: 3,
        blockers: [],
        notes: "basic hit confirms cleanly without hiding the scene",
      },
    ],
    contacts: [
      {
        event: "basic shot on grunt",
        intensity: "light",
        hitReadable: true,
        forceReadable: true,
        scenePreserved: true,
        audioCoherent: true,
        hitStop: "subtle",
        cameraSupport: "none",
        notes: "clean confirmation",
      },
    ],
    incidents: [
      {
        incidentTag: "combo-toast-hides-dodge-read",
        title: "reward popup competes with dodge lane",
        lenses: ["hud", "failure", "pacing"],
        firstSeenAt: "00:31",
        repeatedCount: 2,
        impact: "medium",
        persistence: "repeatable",
        playerCost: ["confusion", "death", "attention-tax"],
        nextCheck:
          "confirm whether moving or suppressing the toast restores one dominant urgent read during the same wave transition",
        notes: "same overlap appears in busy-frame sample and in one logged death",
      },
    ],
    channelSupport: {
      criticalInfoMultiChannel: true,
      criticalInfoUsesColorOnly: false,
      criticalInfoUsesAudioOnly: false,
      muteCriticalInfoStillPlayable: true,
      criticalInfoHasNonColorBackup: true,
      hapticsUsed: false,
      hapticsConfigurable: false,
      hapticsCarryCriticalInfoAlone: false,
    },
    agiSnapshot: {
      holds: {
        present: false,
        readableBeforeAttempt: true,
        notes: "log whether any hold or charge action is clearly shown before commitment",
      },
      rapidPresses: {
        present: false,
        repeatBurdenReadable: true,
        notes: "log repeated presses only when the action lane really asks for them",
      },
      simultaneousInputs: {
        present: true,
        burdenReadable: true,
        notes: "log whether the player has to press more than one control in the same beat",
      },
      textClarity: {
        clearTextPresent: true,
        smallTextLegibleUnderMotion: true,
        notes: "log whether critical text stays clear without zooming or pausing",
      },
      colorAlternatives: {
        present: true,
        colorOnlyRisk: false,
        notes: "log whether shape, icon, or contrast carries the read when color is removed",
      },
      motionCameraComfort: {
        cameraMotionComfortable: true,
        backgroundMotionComfortable: true,
        notes: "log whether camera motion or background movement makes the scene hard to keep in view",
      },
      starterCommand:
        "bun.cmd .agents/skills/agi-tag-snapshot/scripts/agi_tag_snapshot.ts --observations .local/some-game-playtest.json --json-out .local/some-game-agi-tags.json",
    },
    strengths: ["first action readable without tutorial wall"],
    frictions: ["no in-run control reminder"],
  };
}

export function buildTemplate(): string {
  return [
    "# Playtest Evidence Capture Template",
    "",
    "Use once per short browser-play session. Log observed facts only.",
    "",
    "## Session Checks",
    "",
    "- Cover first contact, one pressure beat, one busy frame, one fail-and-retry when possible.",
    "- Record explicit evidence scope before making design claims.",
    "- Log early-loop cadence once: first meaningful input, first risk, first reward, first retry opportunity.",
    "- Track retries separately from failures so restart friction and lesson return are based on observed re-entry, not inferred from death count.",
    "- Log mastery support once: whether the opening gives one earned success, one readable short goal, and one meaningful early choice.",
    "- When a meaningful choice appears, log the offered options, the expected payoff before commitment, the actual payoff after the pick resolves, and how the result compares against the current state or build.",
    "- When a route, tool, loadout, or risk-reward choice appears, log the offered options, the expected payoff for each legible option, the picked option, the observed payoff, and whether the player could compare the post-pick state against the prior state or skipped options.",
    "- For telegraph reviews, capture one cue sample that names the dangerous space, the implied response, and whether the future path stayed visible under pressure.",
    "- Log raw observations once, then reuse them across focused audit skills.",
    "- Score each probe outcome once with success rating plus confidence, satisfaction, and frustration so later audits can tell task failure apart from low-trust or high-friction success.",
    "- Add lightweight workload ratings to each probe outcome so later audits can separate satisfying depth from success that only happened under overload or rush.",
    "- For must-react cues, note whether the telegraph showed the needed response and future path.",
    "- For critical cues, log which channels carried the read and whether any meaning depended on color alone or audio alone.",
    "- For AGI snapshot prep, also log whether holds, rapid presses, and simultaneous inputs were present; whether critical text stayed clear; whether color alternatives existed; and whether camera or motion stayed comfortable to track.",
    "- For control-surface reviews, log remap scope, whether remaps show back up in prompts, whether hold-toggle alternatives exist, whether sensitivity/inversion/axis controls exist, and whether game-speed or timing relief exists. Keep this lane separate from settings-and-assists so later audits do not blur the scope.",
    "- For settings-and-assists reviews, log live, pause, and post-failure reachability, whether difficulty or assist changes are progress-safe, whether reminders or practice relief can be reopened when needed, and whether the sampled repair path persists across retry.",
    "- Log at least one overlap where several urgent signals compete, including whether one dominant read still survived.",
    "- For pacing, log active demands, fresh demands, and whether the stack stayed readable at the beat that mattered.",
    "- For temporary prompts, log whether critical messages auto-dismiss, whether players can pace them, whether they can be reviewed later, and whether non-critical popups can be suppressed when they obstruct play.",
    "- Log if failure or read problems were confounded by input slip, response lag, camera drift, or obstructed view.",
    "- For failure loops, note whether one mistake chained into repeated punishment and whether retry brought back the same lesson stably enough to test the fix.",
    "- If the same problem appears across probes, add one `incidents` row with a short tag, repeat count, impact, persistence, player cost, and next check so downstream audits inherit one shared priority queue instead of rediscovering the same issue.",
    "- Keep strengths and frictions tied to observed moments, not broad taste claims.",
    "- If you use the busy-frame capture lane, merge the artifact's `observationPatch` into this JSON or pass the artifact to `playtest_evidence_capture.ts --busy-frame-capture`.",
    "- After report generation, use `observation_finding_normalizer.ts` to collapse repeated raw observations into compact finding/action triples with artifact citations, freshness, and claim ceilings.",
    "- After busy-frame logging, use `busy_frame_clutter_smoke.ts` when you need one compact blocker-first verdict on background complexity, overlay competition, and critical-read survival inside the worst sampled frames.",
    "- After busy-frame logging, use `text_motion_smoke.ts` when you need one blocker-first read on text legibility, contrast stability, color-only meaning, and motion-behind-text risk before deeper HUD work.",
    "- Use `cue_redundancy_smoke.ts` when you need one blocker-first read on text-only, sound-only, color-only, or edge-only critical cues before deeper onboarding, HUD, or telegraph work.",
    "- Use `timed_prompt_smoke.ts` when you need one blocker-first read on auto-dismissing tutorial, warning, chat, or objective prompts before deeper activation, HUD, or failure follow-up.",
    "",
    "## Observation JSON",
    "",
    "```json",
    JSON.stringify(buildObservationTemplate(), null, 2),
    "```",
    "",
  ].join("\n");
}

export function buildProbeDeck({
  game = "some-game",
  sessionDate = "2026-04-30",
  observationPath = `.local/${game}-playtest.json`,
  reportPath = `${game}/playtest-evidence.md`,
  starterDir = `.local/playtest-starters/${game}`,
}: BuildProbeDeckOptions = {}): string {
  return [
    `# ${game} playtest probe deck`,
    "",
    `session date: ${sessionDate}`,
    `observation file: ${observationPath}`,
    `report file: ${reportPath}`,
    `starter dir: ${starterDir}`,
    "",
    "Use task-based probes, not freeform wandering. Capture only observed facts.",
    "",
    "## Probe 1: first contact",
    "",
    "- Goal: reach first meaningful input and first obvious goal.",
    "- Log: first meaningful input time, first risk time, first reward time, whether prompts blocked play, and whether current goal and next step were easy to restate.",
    "- If the opener offers a route, tool, or risk-reward branch, also log the offered options, expected payoff, picked option, actual payoff, and after-pick comparison against the prior state.",
    "- Stop when: one clean first-contact sample exists.",
    "",
    "## Probe 2: busy frame",
    "",
    "- Goal: reach one high-noise moment with overlapping UI, particles, score toasts, subtitles, or camera motion.",
    "- Log: cue masking, critical info loss, motion distraction, whether one dominant urgent read survived overlap, and whether critical cues depended on color alone or audio alone.",
    `- Shortcut: run \`bun.cmd .agents/skills/playtest-evidence-capture/scripts/busy_frame_capture.ts --slug ${game} --out .local/${game}-busy-frame-capture.json\`, then merge the artifact with \`--busy-frame-capture .local/${game}-busy-frame-capture.json\`.`,
    `- Follow-up: run \`bun.cmd .agents/skills/playtest-evidence-capture/scripts/text_motion_smoke.ts --observations "${observationPath}" --out "${game}/text-motion-smoke.md"\` when you want a quick visibility smoke before a full HUD pass.`,
    `- Follow-up: run \`bun.cmd .agents/skills/playtest-evidence-capture/scripts/cue_redundancy_smoke.ts --observations "${observationPath}" --out "${game}/cue-redundancy-smoke.md"\` when you want a quick cue-channel and placement smoke before a full onboarding, HUD, or telegraph pass.`,
    `- Follow-up: run \`bun.cmd .agents/skills/playtest-evidence-capture/scripts/timed_prompt_smoke.ts --observations "${observationPath}" --out "${game}/timed-prompt-smoke.md"\` when you want a quick timer-affordance smoke before a full activation, HUD, or failure pass.`,
    `- Follow-up: run \`bun.cmd .agents/skills/playtest-evidence-capture/scripts/observation_finding_normalizer.ts --observations "${observationPath}" --starter-dir "${starterDir}" --out "${starterDir}/observation-finding-normalizer.json"\` when you want one compact finding/action packet built from the same raw evidence.`,
    "- Stop when: one peak-clutter sample exists.",
    "",
    "## Probe 3: fail and retry",
    "",
    "- Goal: take one representative failure and replay immediately.",
    "- Log: death readability, corrective-action clarity, retry seconds, menu depth, checkpoint loss, chain punishment, and retry lesson stability.",
    "- Stop when: one full fail-retry loop exists.",
    "",
    "## Probe 4: interruption resume",
    "",
    "- Goal: leave for roughly 30 to 60 seconds during live play, then return.",
    "- Log: whether current goal, controls, and next action recover without menu digging or stale prompt mismatch.",
    "- Stop when: one short-break resume sample exists.",
    "",
    "## Probe 5: contact and payoff",
    "",
    "- Goal: land at least one representative contact or payoff moment.",
    "- Log: hit readability, force readability, scene preservation, audio coherence, hit stop, and camera support.",
    "- Stop when: one contact sample exists.",
    "",
    "## Probe 6: choice moment",
    "",
    "- Goal: capture one meaningful branch when the game offers a real tradeoff instead of a cosmetic click.",
    "- Log: each offered option, the expected payoff before commitment, the selected option, the actual payoff after resolution, and how the result compared against the current state or build.",
    "- Stop when: one fully logged choice moment exists or the session confirms no such branch appeared in scope.",
    "",
    "## Probe 7: control surface",
    "",
    "- Goal: verify remap scope, remap reflection, hold-toggle alternatives, and tuning surfaces without collapsing into settings-and-assists.",
    "- Log: remap scope, whether remaps show back up in prompts, hold-toggle alternatives, sensitivity/inversion/axis controls, game-speed relief, timing relief, and one explicit boundary note against broader assist menus.",
    "- Stop when: one control-surface sample exists.",
    "",
    "## Probe 8: settings and assists",
    "",
    "- Goal: verify recovery trust when the player needs help now, not just whether a settings menu technically exists.",
    "- Log: mid-run reachability, pause reachability, post-failure settings or assist reachability, whether difficulty or assist changes apply without restart, whether progress is preserved, whether controls or objective reminders and tutorial replay exist, whether a practice-relief surface exists, and whether the sampled repair path persists across retry.",
    "- Stop when: one settings-and-assists sample exists.",
    "",
    "## Control-surface review",
    "",
    "- Goal: capture one control-surface sample that separates remap and tuning surfaces from motor-tax burden.",
    "- Log: remap scope, whether remaps appear in prompts, hold-toggle alternatives, sensitivity/inversion/axis controls, game-speed relief, timing relief, and whether the session explicitly checked the boundary from settings-and-assists.",
    "- Stop when: one control-surface sample exists.",
    "",
    "## Settings-and-assists review",
    "",
    "- Goal: capture one recovery-trust sample that stays separate from control-surface tuning and raw motor-tax burden.",
    "- Log: live, pause, and post-failure reachability; progress-safe change behavior; reminder or practice recovery; retry persistence; and one short note that says why this lane is not just remap or difficulty theory.",
    "- Stop when: one settings-and-assists sample exists.",
    "",
    "## Telegraph cue sample",
    "",
    "- Goal: capture one must-react cue under a real or near-real pressure beat.",
    "- Log: dangerous space, implied response, future-path visibility, cue channels, whether the read depended on color or audio alone, and whether the cue stayed readable under motion or overlap.",
    "- Stop when: one telegraph-first cue sample exists.",
    "",
    "## Probe outcome scoring",
    "",
    "- After each probe, add one `probeOutcomes` row in the observation JSON.",
    "- Use `outcome`: `success`, `partial`, or `failed`.",
    "- Use `successRating` on a 0 to 4 scale based on the concrete task goal for that probe.",
    "- Use `confidence`, `satisfaction`, and `frustration` on 1 to 7 scales so later audits can separate clean success from shaky or costly success.",
    "- Use `mentalDemand`, `timePressure`, and `effort` on 1 to 7 scales where 1 is low and 7 is high. Keep this lightweight: enough to spot `worked, but too loaded` beats without turning capture into a lab study.",
    "- Keep blockers concrete and observable.",
    "",
    "## Incident queue",
    "",
    "- When the same issue shows up in more than one probe, add one `incidents` row instead of repeating the same prose in several sections.",
    "- Use a short `incidentTag` and mark `repeatedCount`, `impact`, and `persistence` so later audits can sort repeated catalog blockers before one-off papercuts.",
    "- Use `playerCost` to say what the player actually lost: confusion, damage, death, dead time, lost reward, or attention tax.",
    "- Use `nextCheck` to name the smallest follow-up confirmation that would prove the fix or narrow the root cause.",
    "",
    "## Claim guard",
    "",
    "- Do not call activation trust healthy without Probe 1, Probe 3, and Probe 4.",
    "- Do not call onboarding clean without Probe 1 and Probe 4.",
    "- Do not call HUD readable without Probe 2.",
    "- Do not call failure loop healthy without Probe 3.",
    "- Do not call mastery motivation healthy without Probe 1 plus either Probe 3 or explicit improvement-readback evidence.",
    "- Do not call pacing readable without Probe 1 and Probe 3.",
    "- Do not call impact feel good without Probe 5.",
    "- Do not call control-surface coverage complete without a logged remap/tuning sample and explicit boundary note against settings-and-assists.",
    "- Do not call settings-and-assists recovery trust healthy without a logged live-or-post-failure recovery sample plus change-safety and retry-persistence evidence.",
  ].join("\n");
}
