export const WIDTH = 1280;
export const HEIGHT = 720;
export const DEFAULT_GRASS_TOP = HEIGHT * 0.55;

export const TOWER_DEFS = {
  dart: {
    id: "dart",
    name: "Dart Tower",
    cost: 65,
    range: 136,
    fireRate: 0.52,
    projectileSpeed: 480,
    damage: 1,
    color: "#ffbc42",
    projectileColor: "#fff4bf",
    projectileRadius: 6,
    splash: 0,
    upgrades: [
      { name: "Sharpshot Rack", cost: 70, range: 18, damage: 1 },
      { name: "Triple Tempo", cost: 110, range: 26, damage: 1, fireRateMultiplier: 0.72 },
      { name: "Ricochet Rig", cost: 165, range: 22, damage: 1, fireRateMultiplier: 0.82, unlockTier: 3 },
      { name: "Storm Lattice", cost: 230, range: 28, damage: 2, fireRateMultiplier: 0.76, unlockTier: 5 },
    ],
  },
  bomb: {
    id: "bomb",
    name: "Bomb Tower",
    cost: 130,
    range: 164,
    fireRate: 1.05,
    projectileSpeed: 330,
    damage: 2,
    color: "#ff6b6b",
    projectileColor: "#ff8f8f",
    projectileRadius: 8,
    splash: 54,
    upgrades: [
      { name: "Heavy Shell", cost: 90, damage: 1, splash: 18 },
      { name: "Wide Payload", cost: 140, range: 22, splash: 34, fireRateMultiplier: 0.84 },
      { name: "Shatter Mortar", cost: 190, damage: 2, splash: 28, fireRateMultiplier: 0.82, unlockTier: 3 },
      { name: "Aftershock Rack", cost: 255, damage: 2, splash: 36, range: 26, fireRateMultiplier: 0.78, unlockTier: 5 },
    ],
  },
  glue: {
    id: "glue",
    name: "Glue Tower",
    cost: 95,
    range: 144,
    fireRate: 0.82,
    projectileSpeed: 360,
    damage: 1,
    color: "#6bcB77",
    projectileColor: "#d4ff8b",
    projectileRadius: 7,
    splash: 0,
    slowFactor: 0.55,
    slowDuration: 2.2,
    upgrades: [
      { name: "Grip Mix", cost: 80, range: 18, slowFactor: 0.45, slowDuration: 0.9 },
      { name: "Spread Coat", cost: 125, range: 24, fireRateMultiplier: 0.78, splash: 42, damage: 1, slowFactor: 0.36, slowDuration: 1.3 },
      { name: "Caustic Flood", cost: 175, range: 18, damage: 1, splash: 28, slowFactor: 0.28, slowDuration: 1.5, unlockTier: 3 },
      { name: "Lockdown Resin", cost: 220, range: 24, damage: 1, splash: 34, slowFactor: 0.22, slowDuration: 2, fireRateMultiplier: 0.74, unlockTier: 5 },
    ],
  },
};

export const BLOON_TYPES = {
  red: { id: "red", hp: 1, speed: 56, reward: 1, leak: 1, radius: 16, color: "#ff5252", volatile: false },
  blue: { id: "blue", hp: 2, speed: 72, reward: 2, leak: 1, radius: 17, color: "#4dabf7", volatile: false },
  green: { id: "green", hp: 3, speed: 84, reward: 3, leak: 1, radius: 18, color: "#51cf66", volatile: false },
  yellow: { id: "yellow", hp: 4, speed: 98, reward: 4, leak: 2, radius: 19, color: "#ffd43b", volatile: false },
  violet: {
    id: "violet",
    hp: 7,
    speed: 74,
    reward: 7,
    leak: 3,
    radius: 21,
    color: "#b07dff",
    volatile: false,
    children: { type: "yellow", count: 2, spacing: 22 },
  },
  zebra: {
    id: "zebra",
    hp: 5,
    speed: 110,
    reward: 6,
    leak: 2,
    radius: 20,
    color: "#f4f1de",
    children: { type: "blue", count: 2, spacing: 20 },
  },
  ceramic: {
    id: "ceramic",
    hp: 11,
    speed: 82,
    reward: 10,
    leak: 4,
    radius: 22,
    color: "#b08968",
    children: { type: "violet", count: 2, spacing: 26 },
  },
  gold: { id: "gold", hp: 2, speed: 126, reward: 12, leak: 1, radius: 18, color: "#ffe066", volatile: false, bonusCash: 4 },
  lead: { id: "lead", hp: 8, speed: 64, reward: 9, leak: 3, radius: 21, color: "#96a1ad", volatile: false, armored: true },
  black: { id: "black", hp: 2, speed: 68, reward: 5, leak: 2, radius: 18, color: "#343a40", volatile: true, blastRadius: 72, blastDamage: 2 },
  ember: {
    id: "ember",
    hp: 6,
    speed: 92,
    reward: 8,
    leak: 3,
    radius: 20,
    color: "#ff922b",
    volatile: true,
    blastRadius: 80,
    blastDamage: 1,
    children: { type: "red", count: 3, spacing: 18 },
  },
  marble: {
    id: "marble",
    hp: 18,
    speed: 78,
    reward: 14,
    leak: 5,
    radius: 24,
    color: "#ced4da",
    children: { type: "yellow", count: 3, spacing: 24 },
  },
};

function cloneEntries(entries) {
  return entries.map((entry) => ({
    ...entry,
    ...(entry.pattern ? { pattern: [...entry.pattern] } : {}),
  }));
}

function makeWave(label, reward, entries) {
  return { label, reward, entries: cloneEntries(entries) };
}

const ORCHARD_WAVES = [
  makeWave("Warmup", 14, [{ type: "red", count: 16, spacing: 0.52 }]),
  makeWave("Blue Curve", 18, [{ type: "red", count: 14, spacing: 0.44 }, { type: "blue", count: 12, spacing: 0.52 }]),
  makeWave("Green Push", 24, [{ type: "blue", count: 14, spacing: 0.4 }, { type: "green", count: 12, spacing: 0.48 }]),
  makeWave("Volatile Chain", 32, [{ pattern: ["green", "black"], repeats: 8, spacing: 0.24, gap: 0.42 }, { type: "yellow", count: 10, spacing: 0.48 }]),
  makeWave("Fast Scatter", 38, [{ pattern: ["yellow", "yellow", "black"], repeats: 8, spacing: 0.18, gap: 0.36 }, { type: "yellow", count: 7, spacing: 0.26 }]),
  makeWave("Split Pressure", 48, [{ pattern: ["green", "violet"], repeats: 6, spacing: 0.22, gap: 0.4 }, { pattern: ["black", "green"], repeats: 6, spacing: 0.2, gap: 0.34 }, { type: "gold", count: 5, spacing: 0.36 }]),
  makeWave("Pop Storm", 62, [{ pattern: ["yellow", "black", "yellow"], repeats: 8, spacing: 0.16, gap: 0.32 }, { pattern: ["violet", "black"], repeats: 6, spacing: 0.2, gap: 0.34 }, { type: "gold", count: 6, spacing: 0.3 }]),
  makeWave("Lead Check", 74, [{ pattern: ["yellow", "lead"], repeats: 6, spacing: 0.18, gap: 0.34 }, { pattern: ["black", "zebra"], repeats: 5, spacing: 0.2, gap: 0.36 }, { type: "gold", count: 5, spacing: 0.26 }]),
  makeWave("Ceramic Grind", 88, [{ pattern: ["violet", "black"], repeats: 6, spacing: 0.18, gap: 0.34 }, { pattern: ["ceramic", "lead"], repeats: 5, spacing: 0.2, gap: 0.46 }, { type: "gold", count: 6, spacing: 0.24 }]),
  makeWave("Pressure Ladder", 102, [{ pattern: ["zebra", "yellow", "black"], repeats: 7, spacing: 0.16, gap: 0.26 }, { pattern: ["ceramic", "lead"], repeats: 6, spacing: 0.18, gap: 0.38 }, { pattern: ["gold", "yellow"], repeats: 5, spacing: 0.16, gap: 0.28 }]),
  makeWave("Final Cascade", 120, [{ pattern: ["black", "zebra", "yellow"], repeats: 7, spacing: 0.15, gap: 0.24 }, { pattern: ["violet", "black"], repeats: 7, spacing: 0.18, gap: 0.3 }, { pattern: ["ceramic", "lead", "gold"], repeats: 6, spacing: 0.16, gap: 0.36 }]),
  makeWave("Ember Spill", 138, [{ pattern: ["ember", "yellow", "black"], repeats: 7, spacing: 0.16, gap: 0.26 }, { pattern: ["violet", "ember"], repeats: 6, spacing: 0.18, gap: 0.3 }, { type: "gold", count: 7, spacing: 0.22 }]),
  makeWave("Marble Press", 154, [{ pattern: ["marble", "yellow"], repeats: 6, spacing: 0.18, gap: 0.34 }, { pattern: ["ember", "zebra"], repeats: 7, spacing: 0.16, gap: 0.28 }, { pattern: ["ceramic", "black"], repeats: 6, spacing: 0.18, gap: 0.3 }]),
  makeWave("Overtime Crush", 175, [{ pattern: ["ember", "marble", "yellow"], repeats: 6, spacing: 0.16, gap: 0.26 }, { pattern: ["ceramic", "black", "zebra"], repeats: 7, spacing: 0.16, gap: 0.24 }, { pattern: ["violet", "ember", "lead"], repeats: 7, spacing: 0.17, gap: 0.26 }]),
];

const SPILLWAY_WAVES = [
  makeWave("Silt Wake", 18, [{ type: "blue", count: 14, spacing: 0.48 }, { type: "green", count: 8, spacing: 0.56 }]),
  makeWave("Dam Sprint", 24, [{ pattern: ["green", "yellow"], repeats: 8, spacing: 0.24, gap: 0.38 }, { type: "black", count: 4, spacing: 0.52 }]),
  makeWave("Rattle Line", 32, [{ pattern: ["yellow", "black", "blue"], repeats: 7, spacing: 0.2, gap: 0.34 }, { type: "gold", count: 4, spacing: 0.28 }]),
  makeWave("Spill Surge", 42, [{ pattern: ["violet", "green"], repeats: 6, spacing: 0.22, gap: 0.36 }, { pattern: ["black", "yellow"], repeats: 6, spacing: 0.2, gap: 0.34 }]),
  makeWave("Lead Sluice", 56, [{ pattern: ["lead", "yellow"], repeats: 5, spacing: 0.18, gap: 0.36 }, { pattern: ["zebra", "black"], repeats: 5, spacing: 0.18, gap: 0.32 }, { type: "gold", count: 5, spacing: 0.24 }]),
  makeWave("Crack Pressure", 72, [{ pattern: ["ceramic", "black"], repeats: 5, spacing: 0.18, gap: 0.34 }, { pattern: ["violet", "lead"], repeats: 5, spacing: 0.2, gap: 0.36 }]),
  makeWave("Floodlights", 88, [{ pattern: ["gold", "yellow", "black"], repeats: 7, spacing: 0.16, gap: 0.28 }, { pattern: ["ember", "yellow"], repeats: 5, spacing: 0.18, gap: 0.28 }]),
  makeWave("Gate Shear", 108, [{ pattern: ["marble", "black"], repeats: 4, spacing: 0.22, gap: 0.36 }, { pattern: ["ceramic", "lead", "gold"], repeats: 5, spacing: 0.18, gap: 0.32 }]),
  makeWave("Foam Stack", 126, [{ pattern: ["ember", "zebra", "yellow"], repeats: 6, spacing: 0.16, gap: 0.26 }, { pattern: ["violet", "black", "gold"], repeats: 6, spacing: 0.17, gap: 0.28 }]),
  makeWave("Overtop", 152, [{ pattern: ["marble", "ember", "yellow"], repeats: 5, spacing: 0.16, gap: 0.28 }, { pattern: ["ceramic", "black", "lead"], repeats: 6, spacing: 0.16, gap: 0.28 }, { pattern: ["gold", "zebra"], repeats: 6, spacing: 0.16, gap: 0.24 }]),
];

const NIGHT_WAVES = [
  makeWave("Lantern Test", 22, [{ pattern: ["red", "blue", "green"], repeats: 8, spacing: 0.22, gap: 0.34 }]),
  makeWave("Neon Split", 30, [{ pattern: ["yellow", "violet"], repeats: 6, spacing: 0.22, gap: 0.32 }, { type: "gold", count: 5, spacing: 0.24 }]),
  makeWave("Market Crush", 42, [{ pattern: ["black", "yellow", "zebra"], repeats: 7, spacing: 0.18, gap: 0.28 }, { type: "lead", count: 4, spacing: 0.34 }]),
  makeWave("Rush Circuit", 58, [{ pattern: ["gold", "yellow", "black"], repeats: 7, spacing: 0.16, gap: 0.26 }, { pattern: ["violet", "green"], repeats: 6, spacing: 0.18, gap: 0.3 }]),
  makeWave("Smoke Veil", 74, [{ pattern: ["ember", "yellow"], repeats: 7, spacing: 0.18, gap: 0.28 }, { pattern: ["ceramic", "black"], repeats: 5, spacing: 0.2, gap: 0.34 }]),
  makeWave("Bridge Jam", 96, [{ pattern: ["lead", "lead", "black"], repeats: 5, spacing: 0.18, gap: 0.3 }, { pattern: ["gold", "zebra", "yellow"], repeats: 6, spacing: 0.16, gap: 0.26 }]),
  makeWave("Pulse Grid", 118, [{ pattern: ["marble", "yellow"], repeats: 8, spacing: 0.16, gap: 0.22 }, { pattern: ["ember", "violet", "black"], repeats: 8, spacing: 0.13, gap: 0.18 }]),
  makeWave("After Hours", 146, [{ pattern: ["ceramic", "ember", "gold"], repeats: 8, spacing: 0.13, gap: 0.18 }, { pattern: ["marble", "lead"], repeats: 8, spacing: 0.15, gap: 0.18 }, { pattern: ["black", "zebra", "yellow"], repeats: 9, spacing: 0.12, gap: 0.18 }]),
];

export const OPERATIONS = [
  {
    id: "orchard-bend",
    name: "Operation Orchard Bend",
    label: "Campaign 1",
    summary: "Baseline orchard route. Full 14-wave push, steady unlocks, late marble pressure.",
    flavor: "Best first clear. Builds from lane basics into split-chain chaos without changing rules mid-run.",
    victory: "Orchard line held. Spillway route unlocked.",
    startingCash: 155,
    startingLives: 16,
    intermissionTime: 6.2,
    grassTop: DEFAULT_GRASS_TOP,
    pathPoints: [
      { x: 76, y: 612 },
      { x: 214, y: 612 },
      { x: 214, y: 472 },
      { x: 452, y: 472 },
      { x: 452, y: 598 },
      { x: 756, y: 598 },
      { x: 756, y: 312 },
      { x: 1022, y: 312 },
      { x: 1022, y: 154 },
      { x: 1196, y: 154 },
    ],
    starterPads: [
      { x: 164, y: 430, label: "Start", subtitle: "first bend", detail: "Cheap dart or glue", targetX: 214, targetY: 472 },
      { x: 560, y: 430, label: "Anchor", subtitle: "center pocket", detail: "Bomb covers both lanes", targetX: 452, targetY: 598 },
      { x: 890, y: 430, label: "Late", subtitle: "exit catch", detail: "Save shell coverage", targetX: 1022, targetY: 312 },
    ],
    waves: ORCHARD_WAVES,
    theme: {
      skyTop: "#102f3d",
      skyBottom: "#1f4e5f",
      grass: "#2b6e54",
      grassStripeA: "rgba(255,255,255,0.04)",
      grassStripeB: "rgba(0,0,0,0.06)",
      trackOuter: "#6d7f88",
      trackInner: "#d3e4ec",
      trackDash: "#8aa0aa",
      trackGlow: "rgba(199, 239, 212, 0.2)",
      accent: "#8ce99a",
      panelGlow: "rgba(140, 233, 154, 0.16)",
    },
  },
  {
    id: "spillway-switch",
    name: "Operation Spillway Switch",
    label: "Campaign 2",
    summary: "Tighter floodwall bends. Shorter 10-wave run, faster sends, earlier heavy shells.",
    flavor: "Variety pass. Route compresses sight lines, volatile packs show sooner, gold sprints punish slow openings.",
    victory: "Spillway sealed. Night market route unlocked.",
    startingCash: 190,
    startingLives: 16,
    intermissionTime: 5.5,
    grassTop: DEFAULT_GRASS_TOP,
    pathPoints: [
      { x: 74, y: 608 },
      { x: 308, y: 608 },
      { x: 308, y: 506 },
      { x: 184, y: 506 },
      { x: 184, y: 356 },
      { x: 600, y: 356 },
      { x: 600, y: 564 },
      { x: 920, y: 564 },
      { x: 920, y: 228 },
      { x: 1188, y: 228 },
    ],
    starterPads: [
      { x: 128, y: 430, label: "Start", subtitle: "dam mouth", detail: "Open on the first drop", targetX: 184, targetY: 506 },
      { x: 380, y: 430, label: "Anchor", subtitle: "cross lane", detail: "Glue or bomb sees both turns", targetX: 600, targetY: 356 },
      { x: 702, y: 430, label: "Late", subtitle: "flood gate", detail: "Bank shell cover here", targetX: 920, targetY: 564 },
    ],
    waves: SPILLWAY_WAVES,
    theme: {
      skyTop: "#0f1d37",
      skyBottom: "#26507b",
      grass: "#2c5a5f",
      grassStripeA: "rgba(214,239,255,0.06)",
      grassStripeB: "rgba(0,0,0,0.08)",
      trackOuter: "#60707f",
      trackInner: "#d5e7f2",
      trackDash: "#97afbf",
      trackGlow: "rgba(160, 225, 255, 0.22)",
      accent: "#73d2ff",
      panelGlow: "rgba(115, 210, 255, 0.18)",
    },
  },
  {
    id: "night-market",
    name: "Operation Night Market",
    label: "Campaign 3",
    summary: "Neon finale. Compact 8-wave gauntlet with layered splitters, armor, cash bait, and marble closes.",
    flavor: "Longest-feeling extension per minute. Every wave mixes roles fast, so tower placement and upgrade timing matter more than raw count.",
    victory: "Night market survived. Full campaign cleared.",
    startingCash: 225,
    startingLives: 14,
    intermissionTime: 4.75,
    grassTop: DEFAULT_GRASS_TOP,
    pathPoints: [
      { x: 74, y: 622 },
      { x: 266, y: 622 },
      { x: 266, y: 430 },
      { x: 512, y: 430 },
      { x: 512, y: 548 },
      { x: 814, y: 548 },
      { x: 814, y: 256 },
      { x: 1010, y: 256 },
      { x: 1010, y: 414 },
      { x: 1190, y: 414 },
    ],
    starterPads: [
      { x: 200, y: 430, label: "Start", subtitle: "front lift", detail: "Cheap open, then pivot", targetX: 266, targetY: 430 },
      { x: 620, y: 430, label: "Anchor", subtitle: "market bend", detail: "Main splash pocket", targetX: 512, targetY: 548 },
      { x: 926, y: 430, label: "Late", subtitle: "neon exit", detail: "Hold marble leaks here", targetX: 1010, targetY: 414 },
    ],
    waves: NIGHT_WAVES,
    theme: {
      skyTop: "#190d2f",
      skyBottom: "#3f1f67",
      grass: "#204a46",
      grassStripeA: "rgba(255,122,198,0.06)",
      grassStripeB: "rgba(0,0,0,0.1)",
      trackOuter: "#6e678d",
      trackInner: "#f2d9ff",
      trackDash: "#b4a6d4",
      trackGlow: "rgba(255, 180, 226, 0.22)",
      accent: "#ff7ac6",
      panelGlow: "rgba(255, 122, 198, 0.16)",
    },
  },
];

export const STARTING_OPERATION_INDEX = 0;
export const PLACEMENT_MARGIN = 52;
export const TOWER_SPACING = 54;
